#SPDX-License-Identifier: MIT-0
---
# tasks file for roles/backup

- name: Backup running config
  cisco.ios.iso_config:
    backup: yes
  register: backup_result

- name: Save backupo path
  set_fact:
    backup_path: "{{ backup_result.backup_path }}" 
