$ANSIBLE_VAULT;1.1;AES256
61653930666663316336646137643138623438633135663430613030353461383435346564643864
3035363164363362646565666531326335666261366431630a663034393930363363333536336663
64356238336662616530636463636632303034326433613039653038613362353733616364613234
6162396134303435640a613238326337343132303261636663393563353138623530653833313563
35383631626437306533343066333330663964316262303235333038656232303039333136396436
63363339663735313930346438636139376336633838346165366431656131643738656661306365
633632323435363734306334323864353035
